---

#- name: Add ubuntu user
#  user: 
#   name: ubuntu 
#   password: $6$BX.nsk0Woeb$iDNOEbVIfPWQEn/h335pNH4sWn4yYQM/zBR5VP9LkqBT6uwhqdENsGf9tYeYeFGpzEGBz45zZRABOfb9.SmkB. 
#   group: sudo
#   state: present
#   shell: /bin/bash
#   createhome: yes
   
- name: "Installing required software"
  apt: pkg={{ item }} state=installed
  with_items:
  - gunicorn
  - supervisor
  - python-mysqldb
  - python-falcon

- name: "Making sure supervisor is enabled and started"
  service: name=supervisor state=started enabled=yes

- name: "Creating the folder of the application"
  file: path=/opt/testapp state=directory owner=nobody group=nogroup mode=0755

- name: "Copying the application"
  copy: src=files/testapp.py dest=/opt/testapp/testapp.py owner=nobody group=nogroup mode=0755
  notify:
  - restart-app

- name: "Copying the supervisor config file"
  template: src=files/testapp.conf dest=/etc/supervisor/conf.d/testapp.conf owner=nobody group=nogroup mode=0644
  notify:
  - reread-config
  - restart-app

- name: "Adding IP of dbserver to /etc/hosts"
  lineinfile: name=/etc/hosts line="{{ hostvars['dbserver']['ansible_facts']['eth0']['ipv4']['address'] }} dbserver"

